Projeto Instituição/Models/ErrorViewModel.cs
using System;

namespace ProjetoInstituição.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Projeto Instituição/Models/InstituicaoModel.cs
using ProjetoInstituição.Entidades;
using System.Collections.Generic;

namespace ProjetoInstituição.Models
  
{
    public class InstituicaoModel : Instituicao
    {
        public List<Instituicao> ListaInstituicao { get; set; }
    }
}

Projeto Instituição/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjetoInstituição.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoInstituição.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Projeto Instituição/Controllers/InstituicaoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoInstituição.Entidades;
using System;
using System.Linq;

namespace ProjetoInstituição.Controllers
{
    public class InstituicaoController : Controller
    {

        private readonly Contexto db;

        public InstituicaoController(Contexto contexto)
        {
            db = contexto;
        }



        // GET: InstituicaoController
        public ActionResult Index()
        {
            return View(db.INTITUICAO.ToList());
        }

        // GET: InstituicaoController/Details/5
        public ActionResult Details(int id)
        {
            return View(db.INTITUICAO.Where(a =>a.instId == id).FirstOrDefault());
        }

        // GET: InstituicaoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InstituicaoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Instituicao collection)
        {
            try
            {
                db.INTITUICAO.Add(collection);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InstituicaoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(db.INTITUICAO.Where(a=> a.instId == id).FirstOrDefault());
        }

        // POST: InstituicaoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Instituicao collection)
        {
            try
            {
                db.INTITUICAO.Update(collection);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InstituicaoController/Delete/5
        public ActionResult Delete(int id)
        {
           db.INTITUICAO.Remove(db.INTITUICAO.Where(a => a.instId == id).FirstOrDefault());
           db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Projeto Instituição/Controllers/ProfessorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoInstituição.Entidades;
using ProjetoInstituição.Models;
using System.Linq;

namespace ProjetoInstituição.Controllers
{
    public class ProfessorController : Controller
    {
        private readonly Contexto db;

        public ProfessorController(Contexto Contexto)
        {
            db = Contexto;
        }
        // GET: ProfessorController
        public ActionResult Index()
        {
            return View(db.PROFESSOR.ToList());
        }

        // GET: ProfessorController/Details/5
        public ActionResult Details(int id)
        {
            return View(db.PROFESSOR.Where(a => a.Id == id).FirstOrDefault());
        }

        // GET: ProfessorController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: ProfessorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Professor collection)
        {
            try
            {
                db.PROFESSOR.Add(collection);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProfessorController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(db.PROFESSOR.Where(a => a.Id == id).FirstOrDefault());
        }

        // POST: ProfessorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Professor collection)
        {
            try
            {
                db.PROFESSOR.Update(collection);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProfessorController/Delete/5
        public ActionResult Delete(int id)
        {
            db.PROFESSOR.Remove(db.PROFESSOR.Where(a => a.Id == id).FirstOrDefault());
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Projeto Instituição/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Projeto Instituição/Views/Instituicao/Create.cshtml
@model ProjetoInstituição.Entidades.Instituicao

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-secondary">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projeto Instituição/Views/Instituicao/Details.cshtml
@model ProjetoInstituição.Entidades.Instituicao

@{
    ViewData["Title"] = "Details";
}

<h1>Detales das instituições</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-outline-info">Editar</a> 
    <a asp-action="Index" class="btn btn-outline-secondary">Voltar</a>
</div>

Projeto Instituição/Views/Instituicao/Edit.cshtml
@model ProjetoInstituição.Entidades.Instituicao

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="instId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-secondary">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projeto Instituição/Views/Instituicao/Index.cshtml
@model IEnumerable<ProjetoInstituição.Entidades.Instituicao>

@{
    ViewData["Title"] = "Index";
}

<h1>Area de Instituições</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Criar Nova Instituição</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cidade)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.instId" class="btn btn-outline-info">Editar</a> 
                <a asp-action="Details" asp-route-id="@item.instId" class="btn btn-outline-secondary">Detalhes</a> 
                <a asp-action="Delete" asp-route-id="@item.instId" class="btn btn-outline-danger">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Projeto Instituição/Views/Professor/Create.cshtml
@model ProjetoInstituição.Models.InstituicaoModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Professor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="instId" class="control-label"></label>
                <input asp-for="instId" class="form-control" />
                <span asp-validation-for="instId" class="text-danger"></span>
            </div>
                <label>Materias</label>
                <select name="InstituicaoId" class="form-control">
                    @foreach (var item in Model.ListaInstituicao)
                   {
                        <option value="@item.instId">@item.Nome</option>
                   }
                </select>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projeto Instituição/Views/Professor/Details.cshtml
@model ProjetoInstituição.Entidades.Professor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Professor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Materias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Materias)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit">Edit</a> 
    <a asp-action="Index">Back to List</a>
</div>

Projeto Instituição/Views/Professor/Edit.cshtml
@model ProjetoInstituição.Entidades.Professor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Professor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Materias" class="control-label"></label>
                <input asp-for="Materias" class="form-control" />
                <span asp-validation-for="Materias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projeto Instituição/Views/Professor/Index.cshtml
@model IEnumerable<ProjetoInstituição.Entidades.Professor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Materias)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Materias)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-info">Editar</a> 
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-secondary">Detalhes</a> 
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Projeto Instituição/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto_Instituição</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto_Instituição</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instituicao" asp-action="Index">Instituição</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Index">Professor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Projeto_Instituição - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>